### ISSUE TITLE
Homeアクセス時にリロード画面を表示したい

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#223]
# 概要

Homeアクセス時にリロード画面を表示

# 具体的な内容

Homeアクセス時にクルクル回るリロード画面を表示して、データが取得し終わったら、Cardが表示されるようにする

# 目的

現状Homeアクセスはじめではデータが取得されずにカードが表示されず、ボタンだけ表示されていてキモいから。

# タスク

特になし

# 補足

**Comment by aster-void** [comment]
Skeleton UI というのがあるらしい
https://zenn.dev/imajoriri/articles/60c886585bc4c4
