### ISSUE TITLE
写真のアップロードに時間がかかる

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#234]
## 概要

写真のアップロードに時間がかかる

## 再現手順
1.写真のアップロードをする際に重め（5Mくらい）の画像をあげると、8sくらいかかる

## 修正しないとどう困るか

UIとしてダメ

## 原因

画像ファイルが重いせい？
canvasが重い

## 修正案

- クロップライブラリを入れる
  - canvas以外のやつ
- 画像ファイルを選択した直後に圧縮する
- 今はクロップの丸の位置を変えるごとに、計算しているので、それを切り取りボタンを押した時だけにしたい。

**Comment by aster-void** [comment]
まずクロップとアップロードのどちらに時間がかかっているか計測したいですね。
