### ISSUE TITLE
ファイルベースルーティング(Next.js)

### ISSUE THREAD

**Issue by aster-void** [ut-code/CourseMate#367]
## 概要
ディレクトリベースでルーティングをしたい。

## 期待される動作
App.tsx にそれぞれのコンポネントを書き足さなくてもできるようにしたい。

## 目的
開発環境の改善と、あわよくばロード時間改善

## 解決案
- Tanstack Router
- Next.js

**Comment by naka-12** [comment]
最初にやる

**Comment by aster-void** [comment]
https://github.com/ut-code/CourseMate/pull/512
