### ISSUE TITLE
写真登録で、ファイルサイズの制限が厳しすぎる

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#399]
## 概要

普通の風景写真ですらアップロードできない現状。圧縮がちゃんとできているのなら、制限をとっぱらってもいい
もしくは制限を5Mから拡張するか

**Comment by aster-void** [comment]
あまり大きいファイルを許容しちゃうと、今度はバックエンドが DoS 可能になっちゃうんですよね。
フロントエンド側で軽く圧縮してから送るようにするか。
