### ISSUE TITLE
 同じ授業がある問題

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#410]
## 概要

<img width="451" alt="スクリーンショット 2024-10-06 11 57 29" src="https://github.com/user-attachments/assets/091b84d1-5440-4098-9583-c2c4907bbc9d">

**Comment by naka-12** [comment]
(手動で) 末尾に時間割コードくっつけることでとりあえず解決した。

**Comment by naka-12** [comment]
恒久的な対策ではないので考えたいところ。PEAK 科目はだいたい 2 つある。
