### ISSUE TITLE
bun.lockb がいつも差分が出る

### ISSUE THREAD

**Issue by naka-12** [ut-code/CourseMate#479]

**Comment by aster-void** [comment]
Bun AI に聞いたら、 frozenLockFile オプションを有効にするといいらしいですよ

![Screenshot_20241012_201616_Chrome](https://github.com/user-attachments/assets/6089b0e6-845f-46d4-976a-2496d9945ae5)
![Screenshot_20241012_201612_Chrome](https://github.com/user-attachments/assets/b768cb7f-a8c9-4ff9-bf7f-862a64fde803)

**Comment by naka-12** [comment]
なるほど👀
