### ISSUE TITLE
検索タブを追加する

### ISSUE THREAD

**Issue by aster-void** [ut-code/CourseMate#494]
フォロリクを送れるようにする

## 概要

検索ボックスを作成し、検索したら、一覧でユーザーが表示される
表示されたユーザーにはフォローリクエストを送ったりもできる

## 期待される動作

- 授業を検索すると、その授業を履修しているユーザーを表示させる
- ユーザー名を検索すると、そのユーザーが表示される。

## Todo
- [x] 検索機能を追加
- [x] HumanListItemを変更して、その場でフォロリクを送れるようにする

**Comment by KaichiManabe** [comment]
done by #561
