### ISSUE TITLE
UI フレームワークを考える

### ISSUE THREAD

**Issue by aster-void** [ut-code/CourseMate#501]
## 案

- Tailwind 系
  - Tailwind CSS
  - DaisyUI
- コンポネント系
  - MUI
  - Bootstrap
- ビルダー系
  - Chakra UI
  - Tama GUI https://tamagui.dev/
- Zero CSS 系
  - Pico CSS
- ダウンロード系
  - shadcn/ui

**Comment by naka-12** [comment]
Mantine UI

**Comment by aster-void** [comment]
Tailwind CSS + DaisyUI に決定。
