### ISSUE TITLE
apiKey: import.meta.env.VITE_FIREBASE_API_KEY,などを安全なものに変更する

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#58]
import.meta.env.VITE_FIREBASE_API_KEYの場合、.envファイルに保存された環境変数を参照していますが、環境変数自体はブラウザに配信されるJavaScriptコードに含まれるため、オープンになります。つまり、ビルド後のコードでは、環境変数の値は公開されてしまいます。

Firebaseの設定情報は、通常はクライアント側で使用するために公開されても問題ないですが、~~APIキーなどの情報が公開されてしまうと、悪意のある第三者によって不正利用される可能性があります。~~　←違うっぽい [参考](https://firebase.google.com/docs/projects/api-keys?hl=ja)

by GPT

**Comment by aster-void** [comment]
読み込まれた環境変数は、import.meta.env を経由してクライアントソースコードにも文字列として公開されます。

環境変数が誤ってクライアントに漏れてしまうことを防ぐために、VITE_ から始まる変数のみが Vite で処理されたコードに公開されます。例えば、以下の環境変数だと:

```env
VITE_SOME_KEY=123
DB_PASSWORD=foobar
```

VITE_SOME_KEY だけが import.meta.env.VITE_SOME_KEY としてクライアントソースコードに公開され、DB_PASSWORD は公開されません。

```js
console.log(import.meta.env.VITE_SOME_KEY) // "123"
console.log(import.meta.env.DB_PASSWORD) // undefined
```

**Comment by KaichiManabe** [comment]
今のままでいい
