### ISSUE TITLE
未実装のエンドポイントを実装する

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#59]

**Comment by KaichiManabe** [comment]
パスの修正
- Users以外全て
- 特にリクエストのパスがRestAPI的にまずい


未実装のエンドポイント
- ユーザーが存在するかどうかの（exist）エンドポイントだけ（多分）

**Comment by aster-void** [comment]
パスの修正の方は終わりました。 PR 出てます
