### ISSUE TITLE
requestsタブとfollowersタブは一緒にして、friendsタブにする

### ISSUE THREAD

**Issue by KaichiManabe** [ut-code/CourseMate#96]
分ける必要がそこまでなさそうなので、一緒にする
requestが来ている場合は、その情報が一番上に来るようにする(色をつけてわかりやすいようにするべき)

**Comment by aster-void** [comment]
これ outgoing な request はどこから見ることにするんだっけ。
それとも見ない？

**Comment by KaichiManabe** [comment]
outgoing な request ってなんですか？

**Comment by aster-void** [comment]
自分が送ったリクエストです

**Comment by KaichiManabe** [comment]
作業会かミーティングの時に決めましょうか

**Comment by KaichiManabe** [comment]
done by #135
